dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
install:
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then PILLOW_VERSION=3.4.2; fi
- pip install --verbose pillow${PILLOW_VERSION:+==$PILLOW_VERSION}
- pip install jinja2
- pip install pyflakes
- pip install docutils
script:
- nosetests -v
- private/run-pyflakes
- make
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
