dist: xenial
language: python
jobs:
  include:
  - python: "2.7"
addons:
  apt:
    packages:
    - libsane-dev
    - sane-utils
install:
- pip install --verbose pillow python-sane
- pip install jinja2
- pip install pydiatra pyflakes
- pip install pylint
- pip install docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- nosetests -v
- py2diatra .
- pyflakes .
- private/run-pylint
- make
- private/check-rst
- make install PREFIX=~/.local
- cd /
- scanhelper --version

# vim:ts=2 sts=2 sw=2 et
