dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - libsane-dev
before_install:
- pillow=pillow
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pillow='pillow==3.4.2'; fi
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install --verbose $pillow python-sane
- pip install jinja2
- pip install pydiatra $pyflakes
- pip install docutils
script:
- nosetests -v
- py2diatra .
- pyflakes .
- make
- private/check-rst
- make install PREFIX=~/.local
- cd /
- scanhelper --version

# vim:ts=2 sts=2 sw=2 et
