dist: xenial
language: python
jobs:
  include:
  - python: "2.6"
    dist: trusty
  - python: "2.7"
addons:
  apt:
    packages:
    - libsane-dev
    - sane-utils
before_install:
- pillow=pillow
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pillow='pillow==3.4.2'; fi
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pylint=:; fi
install:
- pip install --verbose $pillow python-sane
- pip install jinja2
- pip install pydiatra $pyflakes
- $if_pylint pip install pylint
- pip install docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- nosetests -v
- py2diatra .
- pyflakes .
- $if_pylint private/run-pylint
- make
- private/check-rst
- make install PREFIX=~/.local
- cd /
- scanhelper --version

# vim:ts=2 sts=2 sw=2 et
