dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pillow_suffix===3.4.2; fi
install:
- pip install --verbose pillow${pillow_suffix}
- pip install jinja2
- pip install pydiatra pyflakes
- pip install docutils
script:
- nosetests -v
- py2diatra .
- pyflakes .
- make
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
