#!/usr/bin/python -u

import sys

basedir = None
if basedir is not None:
    sys.path[:0] = [basedir]

from lib.cli import main  # pylint: disable=wrong-import-position

main(sys.argv)

# vim:ts=4 sts=4 sw=4 et
