#!/usr/bin/python -u
# encoding=UTF-8

# Copyright © 2011-2018 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of scanhelper.
#
# scanhelper is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.
#
# scanhelper is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

import sys

basedir = None
if basedir is not None:
    sys.path[:0] = [basedir]

from lib.cli import main  # pylint: disable=wrong-import-position

main(sys.argv)

# vim:ts=4 sts=4 sw=4 et
