#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2015-2024 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of scanhelper.
#
# scanhelper is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.
#
# scanhelper is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

import argparse
import os
import sys
import tempfile

import PIL.Image

here = os.path.dirname(__file__)
sys.path[:0] = [here + '/..']

from lib import xmp  # pylint: disable=wrong-import-position

class device:
    vendor = '<dummy vendor>'
    model = '<dummy model>'

def dump_xmp(path):
    xmp.write(sys.stdout, path, device, {})

ap = argparse.ArgumentParser()
ap.add_argument('path', metavar='IMAGE', nargs='?')
options = ap.parse_args()
if options.path is None:
    with tempfile.NamedTemporaryFile(prefix='scanhelper.', suffix='.png') as fp:
        with PIL.Image.new('RGB', (23, 42)) as im:
            im.save(fp)
        dump_xmp(fp.name)
else:
    dump_xmp(options.path)

# vim:ts=4 sts=4 sw=4 et
