#!/bin/sh

# Copyright © 2012-2018 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of scanhelper.
#
# scanhelper is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.
#
# scanhelper is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

export version=${1:?"no version number provided"}
set -e -u
set -x
dch -m -v "$version" -u low -c doc/changelog
perl -pi -e 's/^__version__ = '"'"'\K[\w.]+/$ENV{version}/' lib/__init__.py
