name: CI
permissions: {}
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up PATH
      run: |
        PATH+=:~/.local/bin
        echo "$PATH" >> $GITHUB_PATH
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: set up distutils
      run: |
        if ! [ -d ${{env.pythonLocation}}/lib/python*/distutils/ ]; then
          python -m pip install setuptools
          echo SETUPTOOLS_USE_DISTUTILS=local | tee -a $GITHUB_ENV;
        fi
    - name: install deps
      run: |
        sudo apt-get install -y libsane-dev sane-utils
        python -m pip install pillow
        python -m pip install python-sane
        python -m pip install jinja2
    - name: install nose
      run: |
        # work-around for <https://github.com/nose-devs/nose/issues/1115>:
        python -m pip install --upgrade 'setuptools<58'
        case ${{matrix.python}} in 3.*)
          # stolen from <https://github.com/pypa/setuptools/commit/6653e747c3815b14>
          sed -i -e "s/^register_.*[(]pkgutil[.]ImpImporter,/if hasattr(pkgutil, 'ImpImporter'):\\n &/" ${{env.pythonLocation || '/usr/local'}}/lib/python*/*-packages/pkg_resources/__init__.py
        esac
        python -m pip install --upgrade 'wheel<0.38'
        # work-around for <https://github.com/nose-devs/nose/issues/1099>:
        python -m pip install --no-build-isolation --no-binary ':all:' nose
        case ${{matrix.python}} in 3.*)
          # work-around for <https://github.com/nose-devs/nose/issues/1116>:
          sed -i -e 's/ from unittest import _TextTestResult$/ from unittest import TextTestResult as _TextTestResult/' ${{env.pythonLocation || '/usr/local'}}/lib/python*/site-packages/nose/result.py
        esac
        if ! python -c 'import imp'; then
          python -m pip install zombie-imp
        fi
        python -m pip install nose
    - name: run tests
      run: |
        nosetests -v
      timeout-minutes: 1
    - name: build docs
      run: |
        make
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        python -m pip install docutils
        private/check-rst
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra --verbose .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: run pylint
      run: |
        python -m pip install pylint
        private/run-pylint
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: check whether the executable was installed correctly
      run: |
        cd /
        scanhelper --version
        scanhelper --help

# vim:ts=2 sts=2 sw=2 et
