name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up PATH
      run: |
        PATH+=:~/.local/bin
        echo "$PATH" >> $GITHUB_PATH
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: set up Python 2.7
      run: |
        sudo apt-get install python-is-python2 python2-dev
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
        sudo python get-pip.py
        rm get-pip.py
    - name: install deps
      run: |
        sudo apt-get install -y libsane-dev sane-utils
        python -m pip install pillow
        python -m pip install python-sane
        python -m pip install jinja2
    - name: run tests
      run: |
        python -m pip install nose
        nosetests -v
    - name: build docs
      run: |
        make
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        python -m pip install docutils
        private/check-rst
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra --verbose .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: run pylint
      run: |
        python -m pip install pylint
        private/run-pylint
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: check whether the executable was installed correctly
      run: |
        cd /
        scanhelper --version
        scanhelper --help

# vim:ts=2 sts=2 sw=2 et
